import type { Metadata } from "next";
import "./globals.css";
import Topbar from '../components/Topbar';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col bg-white">
        <Topbar />
        <Navbar />
          <main className="flex-grow">
            {children}
          </main>
        <Footer />
      </body>
    </html>
  );
}